language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
# command to run tests
script: nosetests
# Ensure dependencies are installed
install:
  - pip install requests requests_download jinja2 yarg win_cli_launchers testpath
  - if [[ ${TRAVIS_PYTHON_VERSION} == '2.7' ]]; then pip install configparser pathlib; fi
  - if [[ ${TRAVIS_PYTHON_VERSION} == '3.3' ]]; then pip install pathlib; fi

# Enable new Travis stack, should speed up builds
sudo: false
